import Head from "next/head";
import Link from "next/link";
import NavBar from "./NavBar";

import Footer from "./Footer";

function DefaultLayout({ children }: { children?: JSX.Element }) {
    return (
        <div className="w-full">
            <div className="bg-primaryColour w-full overscroll-x-contain ">
                <NavBar />

                <div className="bg-white w-full">
                    <main>
                        <Head>
                            <title>ISSL</title>
                            <meta name="description" content="Generated by create next app" />
                            <link rel="icon" href="/logo.ico" />
                        </Head>


                        {children}

                        <Footer />
                    </main>

                </div>


              
            </div>



        </div>
    )
}

export default DefaultLayout;