import Head from "next/head";
import Link from "next/link";

function DefaultLayout({ children }: { children?: JSX.Element }) {
    return (

        <div className="bg-primaryColour md:py-32 min-h-screen">
            <div className="bg-white max-w-5xl mx-auto py-20 px-10 md:py-20 md:px-20 min-h-screen md:min-h-0">
                <main>
                    <Head>
                        <title>ISSL NEXT</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>

                    {children}
                </main>

            </div>
        </div>
    )
}

export default DefaultLayout;