import Head from "next/head";
import Link from "next/link";
import NavBar from "./NavBar";

import Footer from "./Footer";

function DefaultLayout({ children }: { children?: JSX.Element }) {
    return (
        <div className="w-full gap-y-10">
           
            <div className="bg-primaryColour w-full overscroll-x-contain  ">
            <NavBar />

                <div className="bg-white w-full">
                    <main>
                        <Head>
                            <title>ISSL</title>
                            <meta name="description" content="Generated by create next app" />
                            <link rel="icon" href="/logo.ico" />
                        </Head>


                        {children}

                       
                    </main>
                  
                </div>

            
              
            </div>

            <div className="pt-5">
            <Footer />
            </div>
            
          
            

            

           

        </div>
    )
}

export default DefaultLayout;